language: scala
scala:
    - "2.10.4"
env:
    global:
        - COURSIER_NO_TERM=1
        - TOREE_RESOLUTION_VERBOSITY=0
jdk:
    - oraclejdk7
    - openjdk7

script:
    - make test-travis

sudo: false

cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot/
        - $HOME/.coursier/cache/v1

branches:
    only:
        - master

